// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Lanlink

#ifndef UI_BALANCE_H
#define UI_BALANCE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Balance
extern void ui_Balance_screen_init(void);
extern void ui_Balance_screen_destroy(void);
extern void ui_Balance_screen_relocalize(void);
extern void ui_event_Balance(lv_event_t * e);
extern lv_obj_t * ui_Balance;
extern lv_obj_t * ui_top;
extern lv_obj_t * ui_deeplogo;
extern lv_obj_t * ui_balico;
extern lv_obj_t * ui_balancetop;
extern lv_obj_t * ui_banancePanel;
extern lv_obj_t * ui_baltext;
extern lv_obj_t * ui_balancenum;
extern lv_obj_t * ui_balicon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

