// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Lanlink

#include "../ui.h"

lv_obj_t * ui_Balance = NULL;
lv_obj_t * ui_top = NULL;
lv_obj_t * ui_deeplogo = NULL;
lv_obj_t * ui_balico = NULL;
lv_obj_t * ui_balancetop = NULL;
lv_obj_t * ui_banancePanel = NULL;
lv_obj_t * ui_baltext = NULL;
lv_obj_t * ui_balancenum = NULL;
lv_obj_t * ui_balicon = NULL;
// event funtions
void ui_event_Balance(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        _ui_screen_change(&ui_Server, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Server_screen_init);
    }
}

// build funtions

void ui_Balance_screen_init(void)
{
    ui_Balance = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Balance, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Balance, lv_color_hex(0x2D2E30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Balance, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_top = lv_obj_create(ui_Balance);
    lv_obj_set_width(ui_top, 333);
    lv_obj_set_height(ui_top, 55);
    lv_obj_set_x(ui_top, 0);
    lv_obj_set_y(ui_top, -83);
    lv_obj_set_align(ui_top, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_top, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_deeplogo = lv_image_create(ui_Balance);
    lv_image_set_src(ui_deeplogo, &ui_img_deepseek_png);
    lv_obj_set_width(ui_deeplogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deeplogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deeplogo, -68);
    lv_obj_set_y(ui_deeplogo, -31);
    lv_obj_set_align(ui_deeplogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_deeplogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_deeplogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_balico = lv_image_create(ui_Balance);
    lv_image_set_src(ui_balico, &ui_img_balance_png);
    lv_obj_set_width(ui_balico, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_balico, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_balico, -139);
    lv_obj_set_y(ui_balico, -71);
    lv_obj_set_align(ui_balico, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_balico, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_balico, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_balico, 180);

    ui_balancetop = lv_label_create(ui_Balance);
    lv_obj_set_width(ui_balancetop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_balancetop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_balancetop, -85);
    lv_obj_set_y(ui_balancetop, -71);
    lv_obj_set_align(ui_balancetop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_balancetop, "Balance");
    lv_obj_set_style_text_color(ui_balancetop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_balancetop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_balancetop, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_banancePanel = lv_obj_create(ui_Balance);
    lv_obj_set_width(ui_banancePanel, 264);
    lv_obj_set_height(ui_banancePanel, 71);
    lv_obj_set_x(ui_banancePanel, 0);
    lv_obj_set_y(ui_banancePanel, 30);
    lv_obj_set_align(ui_banancePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_banancePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_banancePanel, lv_color_hex(0xBFDCE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_banancePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_banancePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_banancePanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_baltext = lv_label_create(ui_Balance);
    lv_obj_set_width(ui_baltext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_baltext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_baltext, -98);
    lv_obj_set_y(ui_baltext, 15);
    lv_obj_set_align(ui_baltext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_baltext, "余额");
    lv_obj_set_style_text_color(ui_baltext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_baltext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_baltext, &ui_font_balance22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_balancenum = lv_label_create(ui_Balance);
    lv_obj_set_width(ui_balancenum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_balancenum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_balancenum, -2);
    lv_obj_set_y(ui_balancenum, 30);
    lv_obj_set_align(ui_balancenum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_balancenum, "12.33");
    lv_obj_set_style_text_color(ui_balancenum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_balancenum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_balancenum, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_balicon = lv_label_create(ui_Balance);
    lv_obj_set_width(ui_balicon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_balicon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_balicon, 64);
    lv_obj_set_y(ui_balicon, 38);
    lv_obj_set_align(ui_balicon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_balicon, "¥");
    lv_obj_set_style_text_color(ui_balicon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_balicon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_balicon, &ui_font_balance22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Balance, ui_event_Balance, LV_EVENT_ALL, NULL);

}

void ui_Balance_screen_destroy(void)
{
    if(ui_Balance) lv_obj_del(ui_Balance);

    // NULL screen variables
    ui_Balance = NULL;
    ui_top = NULL;
    ui_deeplogo = NULL;
    ui_balico = NULL;
    ui_balancetop = NULL;
    ui_banancePanel = NULL;
    ui_baltext = NULL;
    ui_balancenum = NULL;
    ui_balicon = NULL;

}

void ui_Balance_screen_relocalize(void)
{
    // label widgets on screen

}
