// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Lanlink

#ifndef UI_CHAT_H
#define UI_CHAT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_chat
extern void ui_chat_screen_init(void);
extern void ui_chat_screen_destroy(void);
extern void ui_chat_screen_relocalize(void);
extern void ui_event_chat(lv_event_t * e);
extern lv_obj_t * ui_chat;
extern lv_obj_t * ui_contextPanel;
extern lv_obj_t * ui_respanel;
extern lv_obj_t * ui_restext;
extern lv_obj_t * ui_mepanel;
extern lv_obj_t * ui_metext;
extern lv_obj_t * ui_TabView3;
extern lv_obj_t * ui_choosemodel;
extern lv_obj_t * ui_pengg;
extern lv_obj_t * ui_deep;
extern lv_obj_t * ui_choose;
extern lv_obj_t * ui_top3;
extern lv_obj_t * ui_chattop;
extern lv_obj_t * ui_chatico2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

