// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Lanlink

#include "../ui.h"

lv_obj_t * ui_chat = NULL;
lv_obj_t * ui_contextPanel = NULL;
lv_obj_t * ui_respanel = NULL;
lv_obj_t * ui_restext = NULL;
lv_obj_t * ui_mepanel = NULL;
lv_obj_t * ui_metext = NULL;
lv_obj_t * ui_TabView3 = NULL;
lv_obj_t * ui_choosemodel = NULL;
lv_obj_t * ui_pengg = NULL;
lv_obj_t * ui_deep = NULL;
lv_obj_t * ui_choose = NULL;
lv_obj_t * ui_top3 = NULL;
lv_obj_t * ui_chattop = NULL;
lv_obj_t * ui_chatico2 = NULL;
// event funtions
void ui_event_chat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        _ui_screen_change(&ui_home, LV_SCREEN_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_home_screen_init);
    }
}

// build funtions

void ui_chat_screen_init(void)
{
    ui_chat = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_chat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contextPanel = lv_obj_create(ui_chat);
    lv_obj_set_width(ui_contextPanel, 321);
    lv_obj_set_height(ui_contextPanel, 149);
    lv_obj_set_x(ui_contextPanel, 0);
    lv_obj_set_y(ui_contextPanel, 13);
    lv_obj_set_align(ui_contextPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contextPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contextPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_contextPanel, lv_color_hex(0x292C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contextPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_contextPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_contextPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contextPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_respanel = lv_obj_create(ui_contextPanel);
    lv_obj_set_width(ui_respanel, LV_SIZE_CONTENT);   /// 209
    lv_obj_set_height(ui_respanel, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_respanel, -132);
    lv_obj_set_y(ui_respanel, -29);
    lv_obj_set_align(ui_respanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_respanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_respanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_respanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_respanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_respanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_restext = lv_label_create(ui_respanel);
    lv_obj_set_width(ui_restext, 274);
    lv_obj_set_height(ui_restext, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_restext, 1);
    lv_obj_set_y(ui_restext, -2);
    lv_label_set_text(ui_restext, "你好呀hello");
    lv_obj_set_style_text_color(ui_restext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_restext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_restext, &ui_font_ch14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mepanel = lv_obj_create(ui_contextPanel);
    lv_obj_set_width(ui_mepanel, LV_SIZE_CONTENT);   /// 209
    lv_obj_set_height(ui_mepanel, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_mepanel, -132);
    lv_obj_set_y(ui_mepanel, -20);
    lv_obj_set_align(ui_mepanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_mepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mepanel, lv_color_hex(0x69F578), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_mepanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_mepanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_mepanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_mepanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_metext = lv_label_create(ui_mepanel);
    lv_obj_set_width(ui_metext, 274);
    lv_obj_set_height(ui_metext, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_metext, 1);
    lv_obj_set_y(ui_metext, -2);
    lv_label_set_text(ui_metext, "hello呀");
    lv_obj_set_style_text_color(ui_metext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_metext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_metext, &ui_font_ch14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView3 = lv_tabview_create(ui_chat);
    lv_tabview_set_tab_bar_size(ui_TabView3, 30);
    lv_obj_set_width(ui_TabView3, 209);
    lv_obj_set_height(ui_TabView3, 120);
    lv_obj_set_x(ui_TabView3, -2);
    lv_obj_set_y(ui_TabView3, -3);
    lv_obj_set_align(ui_TabView3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_TabView3), lv_color_hex(0x4A4C52),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_TabView3), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosemodel = lv_tabview_add_tab(ui_TabView3, "choose model");
    lv_obj_remove_flag(ui_choosemodel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pengg = lv_image_create(ui_choosemodel);
    lv_image_set_src(ui_pengg, &ui_img_penggang_png);
    lv_obj_set_height(ui_pengg, 136);
    lv_obj_set_width(ui_pengg, LV_SIZE_CONTENT);   /// 65
    lv_obj_set_x(ui_pengg, -48);
    lv_obj_set_y(ui_pengg, -6);
    lv_obj_set_align(ui_pengg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pengg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_pengg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_pengg, 120);
    lv_image_set_inner_align(ui_pengg, LV_IMAGE_ALIGN_TOP_LEFT);

    ui_deep = lv_image_create(ui_choosemodel);
    lv_image_set_src(ui_deep, &ui_img_1529199040);
    lv_obj_set_width(ui_deep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deep, 46);
    lv_obj_set_y(ui_deep, 0);
    lv_obj_set_align(ui_deep, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_deep, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_deep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_deep, 150);

    ui_choose = lv_obj_create(ui_choosemodel);
    lv_obj_remove_style_all(ui_choose);
    lv_obj_set_width(ui_choose, 68);
    lv_obj_set_height(ui_choose, 64);
    lv_obj_set_x(ui_choose, -46);
    lv_obj_set_y(ui_choose, 1);
    lv_obj_set_align(ui_choose, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_choose, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_choose, lv_color_hex(0xBDDEE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_choose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_choose, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_choose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_top3 = lv_obj_create(ui_chat);
    lv_obj_set_width(ui_top3, 333);
    lv_obj_set_height(ui_top3, 53);
    lv_obj_set_x(ui_top3, 0);
    lv_obj_set_y(ui_top3, -83);
    lv_obj_set_align(ui_top3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_top3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chattop = lv_label_create(ui_chat);
    lv_obj_set_width(ui_chattop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chattop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chattop, -99);
    lv_obj_set_y(ui_chattop, -71);
    lv_obj_set_align(ui_chattop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_chattop, "Chat");
    lv_obj_set_style_text_color(ui_chattop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chattop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chattop, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chatico2 = lv_image_create(ui_chat);
    lv_image_set_src(ui_chatico2, &ui_img_message_png);
    lv_obj_set_width(ui_chatico2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chatico2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chatico2, -139);
    lv_obj_set_y(ui_chatico2, -71);
    lv_obj_set_align(ui_chatico2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chatico2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_chatico2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_chatico2, 180);

    lv_obj_add_event_cb(ui_chat, ui_event_chat, LV_EVENT_ALL, NULL);

}

void ui_chat_screen_destroy(void)
{
    if(ui_chat) lv_obj_del(ui_chat);

    // NULL screen variables
    ui_chat = NULL;
    ui_contextPanel = NULL;
    ui_respanel = NULL;
    ui_restext = NULL;
    ui_mepanel = NULL;
    ui_metext = NULL;
    ui_TabView3 = NULL;
    ui_choosemodel = NULL;
    ui_pengg = NULL;
    ui_deep = NULL;
    ui_choose = NULL;
    ui_top3 = NULL;
    ui_chattop = NULL;
    ui_chatico2 = NULL;

}

void ui_chat_screen_relocalize(void)
{
    // label widgets on screen

}
