// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Lanlink

#include "../ui.h"

lv_obj_t * ui_home = NULL;
lv_obj_t * ui_time1 = NULL;
lv_obj_t * ui_time2 = NULL;
lv_obj_t * ui_penggang = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_weatherpart = NULL;
lv_obj_t * ui_weather = NULL;
lv_obj_t * ui_degreeimage = NULL;
lv_obj_t * ui_Weather_kind = NULL;
lv_obj_t * ui_degree = NULL;
lv_obj_t * ui_mmdegree = NULL;
lv_obj_t * ui_battery = NULL;
lv_obj_t * ui_icon = NULL;
// event funtions
void ui_event_home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        rain_Animation(ui_weather, 0);
        panelopen_Animation(ui_weatherpart, 0);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        _ui_screen_change(&ui_chat, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_chat_screen_init);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        _ui_screen_change(&ui_Server, LV_SCREEN_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Server_screen_init);
    }
}

// build funtions

void ui_home_screen_init(void)
{
    ui_home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_home, lv_color_hex(0x292C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time1 = lv_label_create(ui_home);
    lv_obj_set_width(ui_time1, 227);
    lv_obj_set_height(ui_time1, 52);
    lv_obj_set_x(ui_time1, 10);
    lv_obj_set_y(ui_time1, -105);
    lv_obj_set_align(ui_time1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_time1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_time1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_time1, _("06:13"));
    lv_obj_set_style_text_color(ui_time1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_time1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time1, &ui_font_time64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time2 = lv_label_create(ui_home);
    lv_obj_set_width(ui_time2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time2, 110);
    lv_obj_set_y(ui_time2, -48);
    lv_obj_set_align(ui_time2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time2, "20");
    lv_obj_set_style_text_color(ui_time2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time2, &ui_font_time40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_penggang = lv_image_create(ui_home);
    lv_image_set_src(ui_penggang, &ui_img_penggang_png);
    lv_obj_set_width(ui_penggang, 143);
    lv_obj_set_height(ui_penggang, 139);
    lv_obj_set_x(ui_penggang, 91);
    lv_obj_set_y(ui_penggang, 23);
    lv_obj_set_align(ui_penggang, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_penggang, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_penggang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_penggang, 10, 1);
    lv_image_set_scale(ui_penggang, 220);
    lv_image_set_inner_align(ui_penggang, LV_IMAGE_ALIGN_TILE);

    ui_date = lv_label_create(ui_home);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, -57);
    lv_obj_set_y(ui_date, 1);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "12月30日 星期四");
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_date, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_date, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_date, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &ui_font_date22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherpart = lv_obj_create(ui_home);
    lv_obj_set_width(ui_weatherpart, 0);
    lv_obj_set_height(ui_weatherpart, 53);
    lv_obj_set_x(ui_weatherpart, -60);
    lv_obj_set_y(ui_weatherpart, 48);
    lv_obj_set_align(ui_weatherpart, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_weatherpart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weatherpart, lv_color_hex(0x4B4F52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weatherpart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather = lv_image_create(ui_weatherpart);
    lv_image_set_src(ui_weather, &ui_img_frame_00_png);
    lv_obj_set_width(ui_weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather, -61);
    lv_obj_set_y(ui_weather, 1);
    lv_obj_set_align(ui_weather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_weather, 190);

    ui_degreeimage = lv_image_create(ui_weatherpart);
    lv_image_set_src(ui_degreeimage, &ui_img_1926284110);
    lv_obj_set_width(ui_degreeimage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_degreeimage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_degreeimage, -2);
    lv_obj_set_y(ui_degreeimage, -13);
    lv_obj_set_align(ui_degreeimage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_degreeimage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_degreeimage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather_kind = lv_label_create(ui_weatherpart);
    lv_obj_set_width(ui_Weather_kind, 72);
    lv_obj_set_height(ui_Weather_kind, 18);
    lv_obj_set_x(ui_Weather_kind, 48);
    lv_obj_set_y(ui_Weather_kind, -7);
    lv_obj_set_align(ui_Weather_kind, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_kind, "小雨");
    lv_obj_set_style_text_color(ui_Weather_kind, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_kind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Weather_kind, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_kind, &ui_font_weather18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_degree = lv_label_create(ui_weatherpart);
    lv_obj_set_width(ui_degree, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_degree, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_degree, -23);
    lv_obj_set_y(ui_degree, -6);
    lv_obj_set_align(ui_degree, LV_ALIGN_CENTER);
    lv_label_set_text(ui_degree, "18");
    lv_obj_set_style_text_color(ui_degree, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_degree, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_degree, &ui_font_date22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mmdegree = lv_label_create(ui_weatherpart);
    lv_obj_set_width(ui_mmdegree, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mmdegree, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mmdegree, 0);
    lv_obj_set_y(ui_mmdegree, 14);
    lv_obj_set_align(ui_mmdegree, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mmdegree, "10°C~20°C");
    lv_obj_set_style_text_color(ui_mmdegree, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mmdegree, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mmdegree, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery = lv_label_create(ui_home);
    lv_obj_set_width(ui_battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battery, 138);
    lv_obj_set_y(ui_battery, -75);
    lv_obj_set_align(ui_battery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battery, "37%");
    lv_obj_set_style_text_color(ui_battery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_battery, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_battery, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon = lv_label_create(ui_home);
    lv_obj_set_width(ui_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_icon, 95);
    lv_obj_set_y(ui_icon, -74);
    lv_obj_set_align(ui_icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_icon, "");
    lv_obj_set_style_text_color(ui_icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_icon, &ui_font_icon18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_home, ui_event_home, LV_EVENT_ALL, NULL);

}

void ui_home_screen_destroy(void)
{
    if(ui_home) lv_obj_del(ui_home);

    // NULL screen variables
    ui_home = NULL;
    ui_time1 = NULL;
    ui_time2 = NULL;
    ui_penggang = NULL;
    ui_date = NULL;
    ui_weatherpart = NULL;
    ui_weather = NULL;
    ui_degreeimage = NULL;
    ui_Weather_kind = NULL;
    ui_degree = NULL;
    ui_mmdegree = NULL;
    ui_battery = NULL;
    ui_icon = NULL;

}

void ui_home_screen_relocalize(void)
{
    // label widgets on screen
    if((ui_time1) && lv_obj_is_valid(ui_time1)) lv_label_set_text(ui_time1, _("06:13"));

}
