// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Lanlink

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home
extern void ui_home_screen_init(void);
extern void ui_home_screen_destroy(void);
extern void ui_home_screen_relocalize(void);
extern void ui_event_home(lv_event_t * e);
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_time1;
extern lv_obj_t * ui_time2;
extern lv_obj_t * ui_penggang;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_weatherpart;
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_degreeimage;
extern lv_obj_t * ui_Weather_kind;
extern lv_obj_t * ui_degree;
extern lv_obj_t * ui_mmdegree;
extern lv_obj_t * ui_battery;
extern lv_obj_t * ui_icon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

