// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Lanlink

#include "../ui.h"

lv_obj_t * ui_main = NULL;
lv_obj_t * ui_Lan = NULL;
lv_obj_t * ui_lighting = NULL;
lv_obj_t * ui_link = NULL;
lv_obj_t * ui_loading = NULL;
lv_obj_t * ui_loadingtext = NULL;
// event funtions
void ui_event_main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        loading_Animation(ui_loading, 2000);
        lightingshow_Animation(ui_lighting, 0);
        linkshow_Animation(ui_link, 500);
        Lanshow_Animation(ui_Lan, 500);
        longingext_Animation(ui_loadingtext, 2000);
        _ui_screen_change(&ui_home, LV_SCREEN_LOAD_ANIM_FADE_ON, 500, 7000, &ui_home_screen_init);
    }
}

// build funtions

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_main, lv_color_hex(0x2D2E30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lan = lv_image_create(ui_main);
    lv_image_set_src(ui_Lan, &ui_img_lan_png);
    lv_obj_set_width(ui_Lan, 223);
    lv_obj_set_height(ui_Lan, 113);
    lv_obj_set_x(ui_Lan, -47);
    lv_obj_set_y(ui_Lan, -4);
    lv_obj_set_align(ui_Lan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Lan, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Lan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Lan, 220);
    lv_image_set_inner_align(ui_Lan, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_blend_mode(ui_Lan, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Lan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lighting = lv_image_create(ui_main);
    lv_image_set_src(ui_lighting, &ui_img_lighting_png);
    lv_obj_set_width(ui_lighting, 150);
    lv_obj_set_height(ui_lighting, 150);
    lv_obj_set_x(ui_lighting, 3);
    lv_obj_set_y(ui_lighting, 7);
    lv_obj_set_align(ui_lighting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lighting, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_lighting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_lighting, 220);
    lv_image_set_inner_align(ui_lighting, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_blend_mode(ui_lighting, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_lighting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_link = lv_image_create(ui_main);
    lv_image_set_src(ui_link, &ui_img_link_png);
    lv_obj_set_width(ui_link, 170);
    lv_obj_set_height(ui_link, 113);
    lv_obj_set_x(ui_link, 43);
    lv_obj_set_y(ui_link, -4);
    lv_obj_set_align(ui_link, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_link, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_link, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_link, 220);
    lv_image_set_inner_align(ui_link, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_blend_mode(ui_link, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_link, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loading = lv_image_create(ui_main);
    lv_image_set_src(ui_loading, &ui_img_loading_png);
    lv_obj_set_width(ui_loading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_loading, -190);
    lv_obj_set_y(ui_loading, 61);
    lv_obj_set_align(ui_loading, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loading, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_loading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_loading, 190);

    ui_loadingtext = lv_label_create(ui_main);
    lv_obj_set_width(ui_loadingtext, 249);
    lv_obj_set_height(ui_loadingtext, 20);
    lv_obj_set_x(ui_loadingtext, 16);
    lv_obj_set_y(ui_loadingtext, 63);
    lv_obj_set_align(ui_loadingtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loadingtext, "loading...");
    lv_obj_set_style_text_color(ui_loadingtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_loadingtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_loadingtext, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_loadingtext, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_loadingtext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_main, ui_event_main, LV_EVENT_ALL, NULL);

}

void ui_main_screen_destroy(void)
{
    if(ui_main) lv_obj_del(ui_main);

    // NULL screen variables
    ui_main = NULL;
    ui_Lan = NULL;
    ui_lighting = NULL;
    ui_link = NULL;
    ui_loading = NULL;
    ui_loadingtext = NULL;

}

void ui_main_screen_relocalize(void)
{
    // label widgets on screen

}
