// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Lanlink

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main
extern void ui_main_screen_init(void);
extern void ui_main_screen_destroy(void);
extern void ui_main_screen_relocalize(void);
extern void ui_event_main(lv_event_t * e);
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_Lan;
extern lv_obj_t * ui_lighting;
extern lv_obj_t * ui_link;
extern lv_obj_t * ui_loading;
extern lv_obj_t * ui_loadingtext;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

