// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Lanlink

#ifndef UI_SERVER_H
#define UI_SERVER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Server
extern void ui_Server_screen_init(void);
extern void ui_Server_screen_destroy(void);
extern void ui_Server_screen_relocalize(void);
extern void ui_event_Server(lv_event_t * e);
extern lv_obj_t * ui_Server;
extern lv_obj_t * ui_top2;
extern lv_obj_t * ui_serico;
extern lv_obj_t * ui_Servertop;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_cputext;
extern lv_obj_t * ui_CPU;
extern lv_obj_t * ui_cpuarc;
extern lv_obj_t * ui_cups;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_ram;
extern lv_obj_t * ui_ramnum;
extern lv_obj_t * ui_rambar;
extern lv_obj_t * ui_ramtext;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_DISC;
extern lv_obj_t * ui_disknum;
extern lv_obj_t * ui_diskbar;
extern lv_obj_t * ui_dixktext;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_ram2;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Chart2_Xaxis;
extern lv_obj_t * ui_Chart2_Yaxis1;
extern lv_obj_t * ui_Chart2_Yaxis2;
extern lv_obj_t * ui_upico;
extern lv_obj_t * ui_downico;
extern lv_obj_t * ui_upnum;
extern lv_obj_t * ui_downnum;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

