// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Lanlink

#include "../ui.h"

lv_obj_t * ui_Server = NULL;
lv_obj_t * ui_top2 = NULL;
lv_obj_t * ui_serico = NULL;
lv_obj_t * ui_Servertop = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_cputext = NULL;
lv_obj_t * ui_CPU = NULL;
lv_obj_t * ui_cpuarc = NULL;
lv_obj_t * ui_cups = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_ram = NULL;
lv_obj_t * ui_ramnum = NULL;
lv_obj_t * ui_rambar = NULL;
lv_obj_t * ui_ramtext = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_DISC = NULL;
lv_obj_t * ui_disknum = NULL;
lv_obj_t * ui_diskbar = NULL;
lv_obj_t * ui_dixktext = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_ram2 = NULL;
lv_obj_t * ui_Chart2 = NULL;
lv_obj_t * ui_Chart2_Xaxis = NULL;
lv_obj_t * ui_Chart2_Yaxis1 = NULL;
lv_obj_t * ui_Chart2_Yaxis2 = NULL;
lv_obj_t * ui_upico = NULL;
lv_obj_t * ui_downico = NULL;
lv_obj_t * ui_upnum = NULL;
lv_obj_t * ui_downnum = NULL;
// event funtions
void ui_event_Server(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        _ui_screen_change(&ui_home, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_home_screen_init);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        _ui_screen_change(&ui_Balance, LV_SCREEN_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Balance_screen_init);
    }
}

// build funtions

void ui_Server_screen_init(void)
{
    ui_Server = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Server, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Server, lv_color_hex(0x2D2E30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Server, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_top2 = lv_obj_create(ui_Server);
    lv_obj_set_width(ui_top2, 333);
    lv_obj_set_height(ui_top2, 55);
    lv_obj_set_x(ui_top2, 0);
    lv_obj_set_y(ui_top2, -83);
    lv_obj_set_align(ui_top2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_top2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_serico = lv_image_create(ui_Server);
    lv_image_set_src(ui_serico, &ui_img_1230237158);
    lv_obj_set_width(ui_serico, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_serico, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_serico, -139);
    lv_obj_set_y(ui_serico, -71);
    lv_obj_set_align(ui_serico, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_serico, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_serico, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_serico, 180);

    ui_Servertop = lv_label_create(ui_Server);
    lv_obj_set_width(ui_Servertop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Servertop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Servertop, -92);
    lv_obj_set_y(ui_Servertop, -71);
    lv_obj_set_align(ui_Servertop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Servertop, "Server");
    lv_obj_set_style_text_color(ui_Servertop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Servertop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Servertop, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Server);
    lv_obj_set_width(ui_Panel5, 142);
    lv_obj_set_height(ui_Panel5, 59);
    lv_obj_set_x(ui_Panel5, -78);
    lv_obj_set_y(ui_Panel5, -20);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x292931), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0xBFDCE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cputext = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_cputext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cputext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cputext, -46);
    lv_obj_set_y(ui_cputext, -14);
    lv_obj_set_align(ui_cputext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cputext, "CPU");

    ui_CPU = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_CPU, 56);
    lv_obj_set_height(ui_CPU, 25);
    lv_obj_set_x(ui_CPU, -29);
    lv_obj_set_y(ui_CPU, 8);
    lv_obj_set_align(ui_CPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CPU, "19%");
    lv_obj_set_style_text_color(ui_CPU, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CPU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CPU, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpuarc = lv_arc_create(ui_Panel5);
    lv_obj_set_width(ui_cpuarc, 46);
    lv_obj_set_height(ui_cpuarc, 46);
    lv_obj_set_x(ui_cpuarc, 32);
    lv_obj_set_y(ui_cpuarc, 1);
    lv_obj_set_align(ui_cpuarc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_cpuarc, 50);
    lv_arc_set_bg_angles(ui_cpuarc, 0, 360);
    lv_arc_set_rotation(ui_cpuarc, 270);
    lv_obj_set_style_arc_color(ui_cpuarc, lv_color_hex(0x394052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_cpuarc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_cpuarc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_cpuarc, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_cpuarc, lv_color_hex(0x62A5FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_cpuarc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_cpuarc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpuarc, lv_color_hex(0x62A5FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpuarc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cpuarc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cpuarc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cpuarc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cpuarc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_cups = lv_label_create(ui_cpuarc);
    lv_obj_set_width(ui_cups, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cups, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cups, 0);
    lv_obj_set_y(ui_cups, 1);
    lv_obj_set_align(ui_cups, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cups, "19%");
    lv_obj_set_style_text_color(ui_cups, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cups, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cups, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Server);
    lv_obj_set_width(ui_Panel2, 142);
    lv_obj_set_height(ui_Panel2, 59);
    lv_obj_set_x(ui_Panel2, 78);
    lv_obj_set_y(ui_Panel2, -20);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x292931), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xBFDCE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ram = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_ram, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ram, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ram, -46);
    lv_obj_set_y(ui_ram, -14);
    lv_obj_set_align(ui_ram, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ram, "RAM");
    lv_obj_set_style_text_color(ui_ram, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ram, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ram, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ramnum = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_ramnum, 51);
    lv_obj_set_height(ui_ramnum, 25);
    lv_obj_set_x(ui_ramnum, 35);
    lv_obj_set_y(ui_ramnum, -7);
    lv_obj_set_align(ui_ramnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ramnum, "91%");
    lv_obj_set_style_text_color(ui_ramnum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ramnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ramnum, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ramnum, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rambar = lv_bar_create(ui_Panel2);
    lv_bar_set_value(ui_rambar, 91, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_rambar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_rambar, 130);
    lv_obj_set_height(ui_rambar, 7);
    lv_obj_set_x(ui_rambar, 0);
    lv_obj_set_y(ui_rambar, 20);
    lv_obj_set_align(ui_rambar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_rambar, lv_color_hex(0x00ACFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rambar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_rambar, lv_color_hex(0xDC2626), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_rambar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_rambar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_rambar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_rambar, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_rambar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_rambar,
                                                                                             lv_obj_get_style_pad_right(ui_rambar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ramtext = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_ramtext, 64);
    lv_obj_set_height(ui_ramtext, 12);
    lv_obj_set_x(ui_ramtext, -24);
    lv_obj_set_y(ui_ramtext, 3);
    lv_obj_set_align(ui_ramtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ramtext, "1.8G / 2G");
    lv_obj_set_style_text_color(ui_ramtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ramtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ramtext, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ramtext, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Server);
    lv_obj_set_width(ui_Panel3, 142);
    lv_obj_set_height(ui_Panel3, 59);
    lv_obj_set_x(ui_Panel3, -78);
    lv_obj_set_y(ui_Panel3, 47);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x292931), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xBFDCE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DISC = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_DISC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DISC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DISC, -46);
    lv_obj_set_y(ui_DISC, -14);
    lv_obj_set_align(ui_DISC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DISC, "Disc");
    lv_obj_set_style_text_color(ui_DISC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DISC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DISC, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_disknum = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_disknum, 51);
    lv_obj_set_height(ui_disknum, 25);
    lv_obj_set_x(ui_disknum, 40);
    lv_obj_set_y(ui_disknum, -8);
    lv_obj_set_align(ui_disknum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_disknum, "91%");
    lv_obj_set_style_text_color(ui_disknum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_disknum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_disknum, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_disknum, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_diskbar = lv_bar_create(ui_Panel3);
    lv_bar_set_value(ui_diskbar, 91, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_diskbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_diskbar, 130);
    lv_obj_set_height(ui_diskbar, 7);
    lv_obj_set_x(ui_diskbar, 0);
    lv_obj_set_y(ui_diskbar, 20);
    lv_obj_set_align(ui_diskbar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_diskbar, lv_color_hex(0x00ACFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_diskbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_diskbar, lv_color_hex(0xDC2626), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_diskbar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_diskbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_diskbar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_diskbar, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_diskbar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_diskbar,
                                                                                              lv_obj_get_style_pad_right(ui_diskbar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_dixktext = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_dixktext, 90);
    lv_obj_set_height(ui_dixktext, 15);
    lv_obj_set_x(ui_dixktext, -16);
    lv_obj_set_y(ui_dixktext, 3);
    lv_obj_set_align(ui_dixktext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dixktext, "33.2G/39.1G");
    lv_obj_set_style_text_color(ui_dixktext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dixktext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dixktext, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Server);
    lv_obj_set_width(ui_Panel4, 142);
    lv_obj_set_height(ui_Panel4, 59);
    lv_obj_set_x(ui_Panel4, 78);
    lv_obj_set_y(ui_Panel4, 47);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x292931), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0xBFDCE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ram2 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_ram2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ram2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ram2, -41);
    lv_obj_set_y(ui_ram2, -14);
    lv_obj_set_align(ui_ram2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ram2, "RX/TX");
    lv_obj_set_style_text_color(ui_ram2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ram2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ram2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_Panel4);
    lv_obj_set_width(ui_Chart2, 76);
    lv_obj_set_height(ui_Chart2, 46);
    lv_obj_set_x(ui_Chart2, 28);
    lv_obj_set_y(ui_Chart2, 1);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart2, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart2, 5);
    lv_chart_set_axis_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 0, 15);

    ui_Chart2_Xaxis = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart2_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart2_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart2_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart2,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart2_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart2_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart2_Xaxis, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Xaxis, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart2_Xaxis, false);
    ui_Chart2_Yaxis1 = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart2_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart2_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart2_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart2,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart2_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_Chart2_Yaxis1,  0, 15);
    lv_scale_set_total_tick_count(ui_Chart2_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Yaxis1, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart2_Yaxis1, false);
    ui_Chart2_Yaxis2 = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart2_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart2_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart2_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart2,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart2_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart2_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_Chart2_Yaxis2, false);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x62A5FF),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 1, 2, 3, 2, 1 };
    lv_chart_set_series_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
    lv_chart_series_t * ui_Chart2_series_2 = lv_chart_add_series(ui_Chart2, lv_color_hex(0xF94848),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_2_array[] = { 3, 3, 1, 8, 15 };
    lv_chart_set_series_ext_y_array(ui_Chart2, ui_Chart2_series_2, ui_Chart2_series_2_array);

    lv_obj_set_style_size(ui_Chart2, 5, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart2, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart2, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_upico = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_upico, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_upico, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_upico, -56);
    lv_obj_set_y(ui_upico, 1);
    lv_obj_set_align(ui_upico, LV_ALIGN_CENTER);
    lv_label_set_text(ui_upico, "⬆");
    lv_obj_set_style_text_color(ui_upico, lv_color_hex(0xFF484A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_upico, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_upico, &ui_font_updown10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_downico = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_downico, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_downico, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_downico, -56);
    lv_obj_set_y(ui_downico, 17);
    lv_obj_set_align(ui_downico, LV_ALIGN_CENTER);
    lv_label_set_text(ui_downico, "⬇");
    lv_obj_set_style_text_color(ui_downico, lv_color_hex(0x5F9EF4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_downico, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_downico, &ui_font_updown10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_upnum = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_upnum, 35);
    lv_obj_set_height(ui_upnum, 14);
    lv_obj_set_x(ui_upnum, -29);
    lv_obj_set_y(ui_upnum, 1);
    lv_obj_set_align(ui_upnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_upnum, "3kb");
    lv_obj_set_style_text_color(ui_upnum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_upnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_upnum, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_upnum, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_downnum = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_downnum, 34);
    lv_obj_set_height(ui_downnum, 15);
    lv_obj_set_x(ui_downnum, -29);
    lv_obj_set_y(ui_downnum, 17);
    lv_obj_set_align(ui_downnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_downnum, "3kb");
    lv_obj_set_style_text_color(ui_downnum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_downnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_downnum, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_downnum, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Server, ui_event_Server, LV_EVENT_ALL, NULL);

}

void ui_Server_screen_destroy(void)
{
    if(ui_Server) lv_obj_del(ui_Server);

    // NULL screen variables
    ui_Server = NULL;
    ui_top2 = NULL;
    ui_serico = NULL;
    ui_Servertop = NULL;
    ui_Panel5 = NULL;
    ui_cputext = NULL;
    ui_CPU = NULL;
    ui_cpuarc = NULL;
    ui_cups = NULL;
    ui_Panel2 = NULL;
    ui_ram = NULL;
    ui_ramnum = NULL;
    ui_rambar = NULL;
    ui_ramtext = NULL;
    ui_Panel3 = NULL;
    ui_DISC = NULL;
    ui_disknum = NULL;
    ui_diskbar = NULL;
    ui_dixktext = NULL;
    ui_Panel4 = NULL;
    ui_ram2 = NULL;
    ui_Chart2 = NULL;
    ui_upico = NULL;
    ui_downico = NULL;
    ui_upnum = NULL;
    ui_downnum = NULL;

}

void ui_Server_screen_relocalize(void)
{
    // label widgets on screen

}
