SET(SOURCES screens/ui_home.c
    screens/ui_main.c
    screens/ui_Balance.c
    screens/ui_Server.c
    screens/ui_chat.c
    ui.c
    components/ui_comp_hook.c
    ui_helpers.c
    images/ui_img_penggang_png.c
    images/ui_img_frame_00_png.c
    images/ui_img_1926284110.c
    images/ui_img_lan_png.c
    images/ui_img_lighting_png.c
    images/ui_img_link_png.c
    images/ui_img_loading_png.c
    images/ui_img_deepseek_png.c
    images/ui_img_balance_png.c
    images/ui_img_1230237158.c
    images/ui_img_1529199040.c
    images/ui_img_message_png.c
    images/ui_img_lighting_1_png.c
    images/ui_img_lighting_2_png.c
    images/ui_img_lighting_3_png.c
    images/ui_img_lighting_4_png.c
    images/ui_img_lighting_5_png.c
    images/ui_img_lighting_6_png.c
    images/ui_img_rain_1_png.c
    images/ui_img_rain_2_png.c
    images/ui_img_rain_3_png.c
    images/ui_img_rain_4_png.c
    images/ui_img_rain_5_png.c
    images/ui_img_rain_6_png.c
    images/ui_img_snow_1_png.c
    images/ui_img_snow_2_png.c
    images/ui_img_snow_3_png.c
    images/ui_img_snow_4_png.c
    images/ui_img_snow_5_png.c
    images/ui_img_snow_6_png.c
    images/ui_img_wind_1_png.c
    images/ui_img_wind_2_png.c
    images/ui_img_wind_3_png.c
    images/ui_img_wind_4_png.c
    images/ui_img_wind_5_png.c
    images/ui_img_wind_6_png.c
    fonts/ui_font_balance22.c
    fonts/ui_font_date22.c
    fonts/ui_font_icon18.c
    fonts/ui_font_time40.c
    fonts/ui_font_time64.c
    fonts/ui_font_updown10.c
    fonts/ui_font_weather18.c
    fonts/ui_font_ch14.c)

add_library(ui ${SOURCES})
