// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Lanlink

#ifndef _LANLINK_UI_H
#define _LANLINK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_home.h"
#include "screens/ui_main.h"
#include "screens/ui_Balance.h"
#include "screens/ui_Server.h"
#include "screens/ui_chat.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * bts_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * rain_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * panelopen_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * snow_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * startgif_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * lightingshow_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Lanshow_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * linkshow_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * loading_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * longingext_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * wind_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * lighting_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_penggang_png);    // assets/penggang.png
LV_IMG_DECLARE(ui_img_frame_00_png);    // assets/frame_00.png
LV_IMG_DECLARE(ui_img_1926284110);    // assets/temperature-celsius.png
LV_IMG_DECLARE(ui_img_lan_png);    // assets/lan.png
LV_IMG_DECLARE(ui_img_lighting_png);    // assets/lighting.png
LV_IMG_DECLARE(ui_img_link_png);    // assets/link.png
LV_IMG_DECLARE(ui_img_loading_png);    // assets/loading.png
LV_IMG_DECLARE(ui_img_deepseek_png);    // assets/DeepSeek.png
LV_IMG_DECLARE(ui_img_balance_png);    // assets/balance.png
LV_IMG_DECLARE(ui_img_1230237158);    // assets/server-36.png
LV_IMG_DECLARE(ui_img_1529199040);    // assets/logo2-96.png
LV_IMG_DECLARE(ui_img_message_png);    // assets/message.png
LV_IMG_DECLARE(ui_img_lighting_1_png);    // assets/lighting_1.png
LV_IMG_DECLARE(ui_img_lighting_2_png);    // assets/lighting_2.png
LV_IMG_DECLARE(ui_img_lighting_3_png);    // assets/lighting_3.png
LV_IMG_DECLARE(ui_img_lighting_4_png);    // assets/lighting_4.png
LV_IMG_DECLARE(ui_img_lighting_5_png);    // assets/lighting_5.png
LV_IMG_DECLARE(ui_img_lighting_6_png);    // assets/lighting_6.png
LV_IMG_DECLARE(ui_img_rain_1_png);    // assets/rain_1.png
LV_IMG_DECLARE(ui_img_rain_2_png);    // assets/rain_2.png
LV_IMG_DECLARE(ui_img_rain_3_png);    // assets/rain_3.png
LV_IMG_DECLARE(ui_img_rain_4_png);    // assets/rain_4.png
LV_IMG_DECLARE(ui_img_rain_5_png);    // assets/rain_5.png
LV_IMG_DECLARE(ui_img_rain_6_png);    // assets/rain_6.png
LV_IMG_DECLARE(ui_img_snow_1_png);    // assets/snow_1.png
LV_IMG_DECLARE(ui_img_snow_2_png);    // assets/snow_2.png
LV_IMG_DECLARE(ui_img_snow_3_png);    // assets/snow_3.png
LV_IMG_DECLARE(ui_img_snow_4_png);    // assets/snow_4.png
LV_IMG_DECLARE(ui_img_snow_5_png);    // assets/snow_5.png
LV_IMG_DECLARE(ui_img_snow_6_png);    // assets/snow_6.png
LV_IMG_DECLARE(ui_img_wind_1_png);    // assets/wind_1.png
LV_IMG_DECLARE(ui_img_wind_2_png);    // assets/wind_2.png
LV_IMG_DECLARE(ui_img_wind_3_png);    // assets/wind_3.png
LV_IMG_DECLARE(ui_img_wind_4_png);    // assets/wind_4.png
LV_IMG_DECLARE(ui_img_wind_5_png);    // assets/wind_5.png
LV_IMG_DECLARE(ui_img_wind_6_png);    // assets/wind_6.png

// FONTS
LV_FONT_DECLARE(ui_font_balance22);
LV_FONT_DECLARE(ui_font_date22);
LV_FONT_DECLARE(ui_font_icon18);
LV_FONT_DECLARE(ui_font_time40);
LV_FONT_DECLARE(ui_font_time64);
LV_FONT_DECLARE(ui_font_updown10);
LV_FONT_DECLARE(ui_font_weather18);
LV_FONT_DECLARE(ui_font_ch14);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
